name: modules/website/services
metadata:
  label: "services"
  groups: [{"id":"20a0f99f-4380-41e6-b9ae-bb60d77762e8","name":"system field","weight":0},{"id":"53b96e08-da4b-4e42-a1d9-f7032d0c3c22","name":"SEO Settings","weight":1},{"id":"13abf116-4dbc-430c-ac12-aab2829619ae","name":"Page Settings","weight":2},{"id":"d494e68d-896b-4174-99a2-b4d2f4594a2e","name":"Service Content","weight":3}]
  is_archived: false
properties:
- name: content_block_1
  type: string
  metadata:
    label: "Content Block 1"
    weight: 13
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "html"
    is_required: false
- name: content_block_2
  type: string
  metadata:
    label: "Content Block 2"
    weight: 16
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "html"
    is_required: false
- name: content_block_3
  type: string
  metadata:
    label: "Content Block 3"
    weight: 19
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "html"
    is_required: false
- name: created_at
  type: string
  metadata:
    label: "Created At"
    weight: 1
    group_id: "20a0f99f-4380-41e6-b9ae-bb60d77762e8"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: deleted_at
  type: string
  metadata:
    label: "Deleted At"
    weight: 3
    group_id: "20a0f99f-4380-41e6-b9ae-bb60d77762e8"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: enabled
  type: boolean
  metadata:
    label: "Enabled"
    weight: 8
    group_id: "13abf116-4dbc-430c-ac12-aab2829619ae"
    ui_element: "toggle"
    is_sortable: true
    placeholder: "Enabled, Disabled"
    is_shown_in_table: true
- name: id
  type: string
  metadata:
    label: "id"
    weight: 0
    group_id: "20a0f99f-4380-41e6-b9ae-bb60d77762e8"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: image_1
  type: upload
  metadata:
    label: "Image 1"
    weight: 14
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "media_image"
    is_required: false
  options:
    acl: public
    cache_control: ""
    content_disposition: inline
- name: image_2
  type: upload
  metadata:
    label: "Image 2"
    weight: 17
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "media_image"
    is_required: false
  options:
    acl: public
    cache_control: ""
    content_disposition: inline
- name: image_3
  type: upload
  metadata:
    label: "Image 3"
    weight: 20
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "media_image"
    is_required: false
  options:
    acl: public
    cache_control: ""
    content_disposition: inline
- name: list_view_image
  type: upload
  metadata:
    label: "List View Image"
    weight: 11
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "media_image"
    is_required: false
  options:
    acl: public
    cache_control: ""
    content_disposition: inline
- name: list_view_text
  type: string
  metadata:
    label: "List View Text"
    weight: 10
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: meta_description
  type: string
  metadata:
    label: "Meta Description"
    weight: 5
    group_id: "53b96e08-da4b-4e42-a1d9-f7032d0c3c22"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: meta_title
  type: string
  metadata:
    label: "Meta Title"
    weight: 4
    group_id: "53b96e08-da4b-4e42-a1d9-f7032d0c3c22"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: service_name
  type: string
  metadata:
    label: "Service Name"
    weight: 6
    group_id: "13abf116-4dbc-430c-ac12-aab2829619ae"
    ui_element: "input"
    is_required: true
    is_sortable: true
    is_searchable: true
    is_shown_in_table: true
- name: slug
  type: string
  metadata:
    label: "Slug"
    weight: 7
    group_id: "13abf116-4dbc-430c-ac12-aab2829619ae"
    ui_element: "input"
    is_required: true
    is_shown_in_table: false
- name: sort_order
  type: integer
  metadata:
    label: "Sort Order"
    weight: 9
    group_id: "13abf116-4dbc-430c-ac12-aab2829619ae"
    ui_element: "number"
    is_required: false
    is_sortable: true
    is_shown_in_table: true
- name: sub_heading_1
  type: string
  metadata:
    label: "Sub Heading 1"
    weight: 12
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: sub_heading_2
  type: string
  metadata:
    label: "Sub Heading 2"
    weight: 15
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: sub_heading_3
  type: string
  metadata:
    label: "Sub Heading 3"
    weight: 18
    group_id: "d494e68d-896b-4174-99a2-b4d2f4594a2e"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
- name: updated_at
  type: string
  metadata:
    label: "Updated At"
    weight: 2
    group_id: "20a0f99f-4380-41e6-b9ae-bb60d77762e8"
    ui_element: "input"
    is_required: false
    is_shown_in_table: false
